# Generated by Django 3.1.5 on 2021-06-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='lnk',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lnk.profile'),
        ),
    ]
