# Generated by Django 3.2.5 on 2021-09-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lnk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_links',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='lnk.social_media'),
        ),
    ]
