# Generated by Django 3.2.5 on 2021-10-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnk', '0002_alter_site_links_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pics',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
